import type { NewConstraintTemplate } from '../schema/widget/03-constraint-templates';

// @MX:NOTE: [AUTO] CONSTRAINT_TEMPLATES — 12 print constraint catalog for Quick Pick seeding (SPEC-WB-003 FR-WB003-09)
// @MX:SPEC: SPEC-WB-003
export const CONSTRAINT_TEMPLATES: ReadonlyArray<NewConstraintTemplate> = [
  {
    templateKey: 'SIZE_RANGE',
    templateNameKo: '사이즈 범위 제약',
    description: '선택 가능한 사이즈 범위를 제한합니다. 특정 규격만 허용하거나 제외합니다.',
    category: 'spec',
    triggerOptionType: 'SIZE',
    triggerOperator: 'in',
    triggerValuesPattern: ['A4', 'A5'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'filter_options', target_option: 'SIZE', allowed_values: ['210x297'] },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'PAPER_COATING_COMPAT',
    templateNameKo: '용지-후가공 호환 제약',
    description: '특정 용지 선택 시 호환되지 않는 후가공 옵션을 제외합니다.',
    category: 'material',
    triggerOptionType: 'PAPER',
    triggerOperator: 'in',
    triggerValuesPattern: ['투명PVC', 'OPP'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'exclude_options', target_option: 'FINISHING', excluded_values: ['UV코팅', '무광코팅'] },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'PRINT_METHOD_DEP',
    templateNameKo: '인쇄방식 의존 제약',
    description: '인쇄방식에 따라 선택 불가한 옵션을 제외합니다.',
    category: 'process',
    triggerOptionType: 'PRINT_TYPE',
    triggerOperator: 'equals',
    triggerValuesPattern: ['단면'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'exclude_options', target_option: 'BINDING', excluded_values: ['중철', '무선철'] },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'BINDING_STRUCT',
    templateNameKo: '제본 구조 제약',
    description: '제본 방식에 따라 필수 옵션을 요구하고 안내 메시지를 표시합니다.',
    category: 'process',
    triggerOptionType: 'BINDING',
    triggerOperator: 'in',
    triggerValuesPattern: ['무선철', '양장'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'show_message', message: '표지와 내지 재질을 각각 선택해 주세요.', level: 'info' },
      { type: 'require_option', target_option: 'COVER_PAPER' },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'QUANTITY_RANGE',
    templateNameKo: '수량 범위 제약',
    description: '특정 조건에서 주문 가능한 수량 범위를 제한합니다.',
    category: 'quantity',
    triggerOptionType: 'PAPER',
    triggerOperator: 'equals',
    triggerValuesPattern: ['아트지 200g'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'filter_options', target_option: 'QUANTITY', min_value: 100, max_value: 5000 },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'FINISHING_DEP',
    templateNameKo: '후가공 의존성 제약',
    description: '특정 후가공 선택 시 연관 옵션을 자동 추가하고 안내 메시지를 표시합니다.',
    category: 'process',
    triggerOptionType: 'FINISHING',
    triggerOperator: 'contains',
    triggerValuesPattern: ['에폭시'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'auto_add', target_option: 'COATING', value: '무광' },
      { type: 'show_message', message: '에폭시 후가공 시 무광코팅이 자동 적용됩니다.', level: 'info' },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'PRICE_CALC_SWITCH',
    templateNameKo: '가격 계산 전환 제약',
    description: '특정 옵션 선택 시 가격 계산 방식을 전환합니다.',
    category: 'pricing',
    triggerOptionType: 'FINISHING',
    triggerOperator: 'contains',
    triggerValuesPattern: ['박', '형압'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'change_price_mode', mode: 'quote_required', message: '별도 견적이 필요한 옵션입니다.' },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'ADDON_PRODUCT',
    templateNameKo: '추가상품 연계 제약',
    description: '특정 옵션 선택 시 관련 추가상품 목록을 표시합니다.',
    category: 'addon',
    triggerOptionType: 'BINDING',
    triggerOperator: 'in',
    triggerValuesPattern: ['무선철', '양장', '중철'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'show_addon_list', addon_group_key: 'BOOK_ACCESSORIES' },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'DELIVERY_IMPACT',
    templateNameKo: '납기 영향 안내 제약',
    description: '납기에 영향을 주는 옵션 선택 시 안내 메시지를 표시합니다.',
    category: 'delivery',
    triggerOptionType: 'FINISHING',
    triggerOperator: 'contains',
    triggerValuesPattern: ['박', '형압', '에폭시'],
    extraConditionsPattern: null,
    actionsPattern: [
      {
        type: 'show_message',
        message: '선택하신 후가공은 추가 납기(+2~3영업일)가 소요됩니다.',
        level: 'warning',
      },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'COLOR_MODE_EXCL',
    templateNameKo: '색상/도수 제약',
    description: '특정 재질 선택 시 사용 불가한 인쇄 도수 옵션을 제외합니다.',
    category: 'process',
    triggerOptionType: 'PAPER',
    triggerOperator: 'in',
    triggerValuesPattern: ['크라프트', '재생지'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'exclude_options', target_option: 'PRINT_TYPE', excluded_values: ['4도', '별색'] },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'COMPOUND_AND_OR',
    templateNameKo: '복합 AND/OR 조건 제약',
    description: '복합 조건(AND/OR 조합)으로 동작하는 제약 템플릿입니다.',
    category: 'compound',
    triggerOptionType: 'SIZE',
    triggerOperator: 'equals',
    triggerValuesPattern: ['A4'],
    extraConditionsPattern: {
      combinator: 'AND',
      conditions: [
        { option_type: 'QUANTITY', operator: 'gte', value: 1000 },
        { option_type: 'PRINT_TYPE', operator: 'in', values: ['4도'] },
      ],
    },
    actionsPattern: [
      {
        type: 'show_message',
        message: 'A4 + 1000부 이상 + 4도 인쇄 시 대량 할인이 적용됩니다.',
        level: 'info',
      },
    ],
    isSystem: true,
    isActive: true,
  },
  {
    templateKey: 'FILE_DATA_GUIDE',
    templateNameKo: '파일/데이터 가이드 제약',
    description: '특정 옵션 선택 시 파일 또는 데이터 가이드를 안내하고 필수 입력 항목을 요구합니다.',
    category: 'file',
    triggerOptionType: 'FINISHING',
    triggerOperator: 'contains',
    triggerValuesPattern: ['에폭시', '박'],
    extraConditionsPattern: null,
    actionsPattern: [
      { type: 'require_option', target_option: 'FOIL_STAMP' },
      {
        type: 'show_message',
        message: '박/에폭시 후가공은 별도의 별색(spot color) 파일이 필요합니다. 작업 가이드를 확인하세요.',
        level: 'warning',
      },
    ],
    isSystem: true,
    isActive: true,
  },
] as const;
