import type { NewOptionElementType } from '../schema/widget/01-element-types';

// Standard option types for Widget Builder (SPEC-WB-001 FR-WB001-05)
// @MX:ANCHOR: [AUTO] 12 standard print option types — foundation for all product recipes.
// @MX:REASON: Seeded on system install; referenced by recipe bindings (SPEC-WB-002+).
export const STANDARD_OPTION_TYPES: ReadonlyArray<NewOptionElementType> = [
  {
    typeKey: 'SIZE',
    typeNameKo: '규격',
    typeNameEn: 'Size',
    uiControl: 'toggle-group',
    optionCategory: 'spec',
    allowsCustom: true,
    displayOrder: 0,
  },
  {
    typeKey: 'PAPER',
    typeNameKo: '재질',
    typeNameEn: 'Paper',
    uiControl: 'select',
    optionCategory: 'material',
    allowsCustom: false,
    displayOrder: 1,
  },
  {
    typeKey: 'PRINT_TYPE',
    typeNameKo: '인쇄도수',
    typeNameEn: 'Print Type',
    uiControl: 'toggle-group',
    optionCategory: 'process',
    allowsCustom: false,
    displayOrder: 2,
  },
  {
    typeKey: 'FINISHING',
    typeNameKo: '후가공',
    typeNameEn: 'Finishing',
    uiControl: 'toggle-multi',
    optionCategory: 'process',
    allowsCustom: false,
    displayOrder: 3,
  },
  {
    typeKey: 'COATING',
    typeNameKo: '코팅',
    typeNameEn: 'Coating',
    uiControl: 'toggle-group',
    optionCategory: 'process',
    allowsCustom: false,
    displayOrder: 4,
  },
  {
    typeKey: 'BINDING',
    typeNameKo: '제본',
    typeNameEn: 'Binding',
    uiControl: 'toggle-group',
    optionCategory: 'process',
    allowsCustom: false,
    displayOrder: 5,
  },
  {
    typeKey: 'QUANTITY',
    typeNameKo: '수량',
    typeNameEn: 'Quantity',
    uiControl: 'number-stepper',
    optionCategory: 'quantity',
    allowsCustom: true,
    displayOrder: 6,
  },
  {
    typeKey: 'PAGE_COUNT',
    typeNameKo: '페이지수',
    typeNameEn: 'Page Count',
    uiControl: 'number-stepper',
    optionCategory: 'spec',
    allowsCustom: false,
    displayOrder: 7,
  },
  {
    typeKey: 'ADD_ON',
    typeNameKo: '부자재',
    typeNameEn: 'Add-on',
    uiControl: 'toggle-multi',
    optionCategory: 'material',
    allowsCustom: false,
    displayOrder: 8,
  },
  {
    typeKey: 'COVER_PAPER',
    typeNameKo: '표지재질',
    typeNameEn: 'Cover Paper',
    uiControl: 'select',
    optionCategory: 'material',
    allowsCustom: false,
    displayOrder: 9,
  },
  {
    typeKey: 'INNER_PAPER',
    typeNameKo: '내지재질',
    typeNameEn: 'Inner Paper',
    uiControl: 'select',
    optionCategory: 'material',
    allowsCustom: false,
    displayOrder: 10,
  },
  {
    typeKey: 'FOIL_STAMP',
    typeNameKo: '박/형압',
    typeNameEn: 'Foil Stamp',
    uiControl: 'collapsible',
    optionCategory: 'group',
    allowsCustom: false,
    displayOrder: 11,
  },
] as const;
